### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by christyanbrayan** [Alexeiabianna/Hora-do-dia#1]
Não sei se você já mexeu com o GitHub Pages, mas acho que seria uma boa você hospedar essa aplicação lá, por ser simples. Aí de repente botar o link em algum site pessoal ou mesmo só para fins de divulgação.
Se quiser eu posso abrir um PR fazendo isso.

**Comment by Alexeiabianna** [comment]
Fala Crystian! Boa dica! não utilizei ainda o Github Pages, tenho testado o Surge.sh conhece? 
Fica a vontade para abri um PR! Estamos juntos! E parabéns pelos teus README's.md Encontrei teu perfil no google por causa deles.

**Comment by christyanbrayan** [comment]
Já tinha ouvido falar! Mas não experimentei ainda, vou testar. Já usei o gh-pages por ser direto do próprio repositório. Vou abrir lá então.
Caramba, não sabia que ficava indexado. Que bom então, e valeu!
